/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;

import clases.Equipo;
import static clases.Main.*;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author BIBPRESTAMOS# 21
 */
public class FrameAgregarEquipo extends javax.swing.JFrame {

    /**
     * Creates new form FrameAgregarEquipo
     */
    DefaultTableModel modelo;
    
    public FrameAgregarEquipo() {
        initComponents();
        llenarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtmarca = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ESTADO = new javax.swing.JLabel();
        txtmodelo = new javax.swing.JTextField();
        txtnserie = new javax.swing.JTextField();
        bguardar = new javax.swing.JButton();
        bvolver = new javax.swing.JButton();
        box_estado = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtabla = new javax.swing.JTable();
        beliminar = new javax.swing.JButton();
        bconsultar = new javax.swing.JButton();
        bbuscar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("MARCA");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 50, -1));
        jPanel1.add(txtmarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 120, -1));

        jLabel3.setText("MODELO");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        jLabel4.setText("NUMERO DE SERIE");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        ESTADO.setText("ESTADO");
        jPanel1.add(ESTADO, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));
        jPanel1.add(txtmodelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 130, -1));
        jPanel1.add(txtnserie, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 130, -1));

        bguardar.setText("GUARDAR");
        bguardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bguardarActionPerformed(evt);
            }
        });
        jPanel1.add(bguardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, -1, -1));

        bvolver.setText("VOLVER");
        bvolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bvolverActionPerformed(evt);
            }
        });
        jPanel1.add(bvolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        box_estado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dañado", "Reparando ", "Bueno " }));
        box_estado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box_estadoActionPerformed(evt);
            }
        });
        jPanel1.add(box_estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, -1, -1));

        jtabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jtabla.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jScrollPane1.setViewportView(jtabla);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 700, 320));

        beliminar.setText("ELIMINAR");
        beliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        beliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beliminarActionPerformed(evt);
            }
        });
        jPanel1.add(beliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, -1, -1));

        bconsultar.setText("MODIFICAR");
        bconsultar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bconsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bconsultarActionPerformed(evt);
            }
        });
        jPanel1.add(bconsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 180, -1, -1));

        bbuscar.setText("BUSCAR");
        bbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbuscarActionPerformed(evt);
            }
        });
        jPanel1.add(bbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 180, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 580));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bguardarActionPerformed
        Equipo equipo = new Equipo("","","","",0);
        
        equipo.setMarca(txtmarca.getText());
         equipo.setModelo(txtmodelo.getText());
        equipo.setNserie(txtnserie.getText());
     
        
        if(equipo.getMarca().isEmpty() || equipo.getModelo().isEmpty() || equipo.getNserie().isEmpty()  ){
            JOptionPane.showMessageDialog(null, "Por favor, recuerde que debe ingresar los datos correpondientes en sus respectivos campos ");
            
        }else{
            equipo.setEstado(box_estado.getSelectedItem().toString());
            equipo.setId(equipos.size());
            equipos.add(equipo);
            JOptionPane.showMessageDialog(this, "El equipo fue agregado con exito con el id: "+equipo.getId());
        }
           
          txtmarca.setText("");
         txtmodelo.setText("");
         txtnserie.setText("");
         
         llenarTabla();
         
         
         
         
         
       
    }//GEN-LAST:event_bguardarActionPerformed

    
    
    private void llenarTabla(){
       
       modelo = new DefaultTableModel(new String[]{"id","marca","modelo","numero de serie","estado","propietario de quipo"},equipos.size());
        jtabla.setModel(modelo);
          
        TableModel modelodatos = jtabla.getModel();
        for(int i = 0;i<equipos.size();i++){
            Equipo equipo = equipos.get(i);
            modelodatos.setValueAt(equipo.getId(), i, 0);
            modelodatos.setValueAt(equipo.getMarca(), i, 1);
            modelodatos.setValueAt(equipo.getModelo(), i, 2);
            modelodatos.setValueAt(equipo.getNserie(), i, 3);
            modelodatos.setValueAt(equipo.getEstado(), i, 4);
        }
    }
    
    
     public void buscar(){
        
      
        
       String doc = JOptionPane.showInputDialog("digite el documento a buscar ");
       
        for(int i = 0; i < equipos.size(); i++)
        {
            if(equipos.get(i).getNserie().equals(String.valueOf(doc))){
          
            JOptionPane.showMessageDialog(null, " la imformacion es "+equipos.get(i).toString());
            
            }else{
                JOptionPane.showMessageDialog(this, "el usuario no fue encontrado");
            } 
        }
        
    }

    
    
    private void box_estadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box_estadoActionPerformed
        
    }//GEN-LAST:event_box_estadoActionPerformed

    private void bvolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bvolverActionPerformed
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bvolverActionPerformed

    private void beliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beliminarActionPerformed
       int fila=jtabla.getSelectedRow();
       if(fila>=0){
           
           equipos.remove(fila);
           JOptionPane.showMessageDialog(null, " Se a eliminado con exito ");
           llenarTabla();
       }
    }//GEN-LAST:event_beliminarActionPerformed

    private void bconsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bconsultarActionPerformed
       Equipo equipo = new Equipo("","","","",0);
        
       int fila = jtabla.getSelectedRow();
       
       equipos.get(fila);
       int conf;
       if(fila>=0){
          conf = JOptionPane.showConfirmDialog(null, " esta seguro de modificar el equipo");
          if(conf==JOptionPane.YES_OPTION){
              equipos.get(fila).setMarca(JOptionPane.showInputDialog("DIgite el nuevo nombre de la marca"));
          }
          if(conf==JOptionPane.NO_OPTION){
              
          }
          if(conf==JOptionPane.CANCEL_OPTION){
              JOptionPane.showMessageDialog(null, "canselado");
          }
          
          
            conf = JOptionPane.showConfirmDialog(null, " esta seguro de modificar el equipo");
          if(conf==JOptionPane.YES_OPTION){
              equipos.get(fila).setModelo(JOptionPane.showInputDialog("DIgite el nuevo nombre de el modelo"));
          }
          if(conf==JOptionPane.NO_OPTION){
              
          }
          if(conf==JOptionPane.CANCEL_OPTION){
              JOptionPane.showMessageDialog(null, "canselado");
          }
          
          
            conf = JOptionPane.showConfirmDialog(null, " esta seguro de modificar el equipo");
          if(conf==JOptionPane.YES_OPTION){
              equipos.get(fila).setNserie(JOptionPane.showInputDialog("DIgite el nuevo nombre de el numeo de serie "));
          }
          if(conf==JOptionPane.NO_OPTION){
              
          }
          if(conf==JOptionPane.CANCEL_OPTION){
              JOptionPane.showMessageDialog(null, "canselado");
          }
          
          
            conf = JOptionPane.showConfirmDialog(null, " esta seguro de modificar el equipo");
          if(conf==JOptionPane.YES_OPTION){
              equipos.get(fila).setEstado(JOptionPane.showInputDialog("DIgite el nuevo nombre del estado"));
          }
          if(conf==JOptionPane.NO_OPTION){
              
          }
          if(conf==JOptionPane.CANCEL_OPTION){
              JOptionPane.showMessageDialog(null, "canselado");
          }
         
         /* equipos.get(fila).setMarca(JOptionPane.showInputDialog("DIgite el nuevo nombre de la marca "));
          equipos.get(fila).setModelo(JOptionPane.showInputDialog("DIgite el nuevo nombre de la modelo "));
          equipos.get(fila).setNserie(JOptionPane.showInputDialog("DIgite el nuevo nombre de la numero de serie  "));
          equipos.get(fila).setEstado(JOptionPane.showInputDialog("DIgite el nuevo nombre de la estado "));
          */
          // equipos.get(fila).setMarca(JOptionPane.showInputDialog(JOptionPane.showConfirmDialog(null, " Estas seguro de modificar el campo de marca"), "Selecione el nuevo nombre "));
          
          // equipos.get(fila).setModelo(JOptionPane.showInputDialog(JOptionPane.showConfirmDialog(null, " Estas seguro de modificar el campo de modelo"), "Selecione el nuevo nombre "));
          // equipos.get(fila).setNserie(JOptionPane.showInputDialog(JOptionPane.showConfirmDialog(null, " Estas seguro de modificar el numero de serie"), "Selecione el nuevo nombre "));
          
           //equipos.get(fila).setEstado( String.valueOf(JOptionPane.showInputDialog(JOptionPane.showConfirmDialog(null, " Estas seguro de modificar el campo de estado"), "Selecione el nuevo nombre ")));
        
       }
           llenarTabla(); 
       
    }//GEN-LAST:event_bconsultarActionPerformed

    private void bbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbuscarActionPerformed
buscar();

    }//GEN-LAST:event_bbuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ESTADO;
    private javax.swing.JButton bbuscar;
    private javax.swing.JButton bconsultar;
    private javax.swing.JButton beliminar;
    private javax.swing.JButton bguardar;
    public static javax.swing.JComboBox<String> box_estado;
    private javax.swing.JButton bvolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtabla;
    public static javax.swing.JTextField txtmarca;
    public static javax.swing.JTextField txtmodelo;
    public static javax.swing.JTextField txtnserie;
    // End of variables declaration//GEN-END:variables
}
