
package Ventanas;

import clases.Usuario;
import static clases.Main.*;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Dario
 */
public class FrameAgregar extends javax.swing.JFrame {

    /**
     * Creates new form FrameAgregar
     */
   
   int filas;
   DefaultTableModel modelo;
  
    
    public FrameAgregar() {
        initComponents();
        llenarTabla();
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bvolver = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtapellido = new javax.swing.JTextField();
        txtdoc = new javax.swing.JTextField();
        txtedad = new javax.swing.JTextField();
        guardar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textdatos = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtabla = new javax.swing.JTable();
        beliminar = new javax.swing.JButton();
        bmodificar = new javax.swing.JButton();
        bbuscar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bvolver.setText("VOLVER");
        bvolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bvolverActionPerformed(evt);
            }
        });
        jPanel1.add(bvolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("NOMBRE");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("APELLIDO");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));
        jPanel1.add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 140, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("EDAD");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("DOCUMENTO");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));
        jPanel1.add(txtapellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 130, -1));
        jPanel1.add(txtdoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 130, -1));
        jPanel1.add(txtedad, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 130, -1));

        guardar.setText("GUARDAR");
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });
        jPanel1.add(guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, -1, -1));

        textdatos.setColumns(20);
        textdatos.setRows(5);
        jScrollPane1.setViewportView(textdatos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 100, 240, 110));

        jtabla.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jtabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jtabla.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jtabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtablaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtabla);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 300, 800, 300));

        beliminar.setText("ELIMINAR");
        beliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beliminarActionPerformed(evt);
            }
        });
        jPanel1.add(beliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, -1, -1));

        bmodificar.setText("MODIFICAR");
        bmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bmodificarActionPerformed(evt);
            }
        });
        jPanel1.add(bmodificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 260, -1, -1));

        bbuscar.setText("BUSCAR");
        bbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbuscarActionPerformed(evt);
            }
        });
        jPanel1.add(bbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 260, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
       guardar();
    }//GEN-LAST:event_guardarActionPerformed

    private void bvolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bvolverActionPerformed
       menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bvolverActionPerformed

    private void beliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beliminarActionPerformed
       int fila = jtabla.getSelectedRow();
       
       if(fila>=0){
            
            usuarios.remove(fila);
            JOptionPane.showMessageDialog(null, "Se elimino con exito ");
            llenarTabla();
        }
        
       
    }//GEN-LAST:event_beliminarActionPerformed

    private void jtablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtablaMouseClicked
/*int selecion = jtabla.getSelectedRow();
        txtnombre.setText(jtabla.getValueAt(selecion, 1).toString());
         txtapellido.setText(jtabla.getValueAt(selecion, 0).toString());
         txtdoc.setText(jtabla.getValueAt(selecion, 0).toString());
          txtedad.setText(jtabla.getValueAt(selecion, 0).toString());
         filas=selecion;   */
         
    }//GEN-LAST:event_jtablaMouseClicked

    private void bmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bmodificarActionPerformed

        modificarUsuario();
    }//GEN-LAST:event_bmodificarActionPerformed

    private void bbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbuscarActionPerformed

        buscar();
        
    }//GEN-LAST:event_bbuscarActionPerformed

    public void buscar(){
        
       // Usuario usuario = new Usuario();
       // UsuarioPersona persona = new UsuarioPersona("","","",0,0,0);
        
       int doc = Integer.parseInt(JOptionPane.showInputDialog("digite el documento a buscar "));
       
        for(int i = 0; i < usuarios.size(); i++)
        {
            if(usuarios.get(i).getDoc() == doc){
          
            JOptionPane.showMessageDialog(null, " la imformacion es "+usuarios.get(i).toString());
            
            }else{
                JOptionPane.showMessageDialog(this, "el usuario no fue encontrado");
            } 
        }
        
    }
    
    
      private void llenarTabla(){
       // creando el jtable
         modelo = new DefaultTableModel(new String[]{"id","nombre","apellido","documento","edad","equipo asignado"},usuarios.size());
        jtabla.setModel(modelo);
          
              // esta funcion recorrera el arraylist para tomar los datos ingresados y ponerlos en jtable 

        
        TableModel modelodatos = jtabla.getModel();
        for(int i = 0;i<usuarios.size();i++){
            Usuario usuario = usuarios.get(i);
            modelodatos.setValueAt(usuario.getId(), i, 0);
            modelodatos.setValueAt(usuario.getNombre(), i, 1);
            modelodatos.setValueAt(usuario.getApellido(), i, 2);
            modelodatos.setValueAt(usuario.getDoc(), i, 3);
            modelodatos.setValueAt(usuario.getEdad(), i, 4);
        }
    }
      
      
      
      public void guardar(){
          
           Usuario usuario = new Usuario("","",0,0,0);
        usuario.setNombre(txtnombre.getText());
        usuario.setApellido(txtapellido.getText());
        try{
             usuario.setDoc(Integer.parseInt(txtdoc.getText()));
             usuario.setEdad(Integer.parseInt(txtedad.getText()));
        }catch(NumberFormatException ex ){
            JOptionPane.showMessageDialog(null, "ERROR "+ ex.getMessage());
        }
        if(usuario.getNombre().isEmpty() || usuario.getApellido().isEmpty() || String.valueOf(usuario.getDoc()).isEmpty() || String.valueOf(usuario.getEdad()).isEmpty() ){
            JOptionPane.showMessageDialog(null, "Por favor, recuerde que debe ingresar los datos correpondientes en sus respectivos campos ");
        }else{
            usuario.setId(clases.Main.usuarios.size());
        
        clases.Main.usuarios.add(usuario);
        
       JOptionPane.showMessageDialog(this, "El usuario fue agregado con exito con el id: "+usuario.getId());
        }
        
        
        
        txtnombre.setText("");
        txtapellido.setText("");
        txtdoc.setText("");
        txtedad.setText("");
        
        textdatos.setText(usuarios.toString());
       
        llenarTabla();
          
      }
      
      
      public void modificarUsuario(){
           
          Usuario usuario = new Usuario("","",0,0,0);
         int fila = jtabla.getSelectedRow();
         int conf;
       usuarios.get(fila);
       
       if(fila>=0){
          
           conf = JOptionPane.showConfirmDialog(null, "Estas seguro de modificar el campo de nombre");
           if(conf==JOptionPane.YES_OPTION){
               usuarios.get(fila).setNombre(JOptionPane.showInputDialog("Selecione el nuevo nombre"));
               
           }
           if(conf==JOptionPane.NO_OPTION){
               
           }
           if(conf==JOptionPane.CANCEL_OPTION){
               JOptionPane.showMessageDialog(null, " Canselado");
      }
           
           
           conf = JOptionPane.showConfirmDialog(null, "Estas seguro de modificar el campo de apellido");
           if(conf==JOptionPane.YES_OPTION){
               
               usuarios.get(fila).setApellido(JOptionPane.showInputDialog("Selecione el nuevo nombre"));
              
              
           }
           if(conf==JOptionPane.NO_OPTION){
               
           }
           if(conf==JOptionPane.CANCEL_OPTION){
               JOptionPane.showMessageDialog(null, " Canselado");
           }
           
           
           conf = JOptionPane.showConfirmDialog(null, "Estas seguro de modificar el campo de su documento");
           if(conf==JOptionPane.YES_OPTION){
              
               usuarios.get(fila).setDoc(Integer.parseInt(JOptionPane.showInputDialog("Selecione el nuevo nombre")) );
               
           }
           if(conf==JOptionPane.NO_OPTION){
               
           }
           if(conf==JOptionPane.CANCEL_OPTION){
               JOptionPane.showMessageDialog(null, " Canselado");
           }
           
           
           
           conf = JOptionPane.showConfirmDialog(null, "Estas seguro de modificar el campo de su edad");
           if(conf==JOptionPane.YES_OPTION){
               
               usuarios.get(fila).setEdad(Integer.parseInt(JOptionPane.showInputDialog("Selecione el nuevo nombre")));
           }
           if(conf==JOptionPane.NO_OPTION){
               
           }
           if(conf==JOptionPane.CANCEL_OPTION){
               JOptionPane.showMessageDialog(null, " Canselado");
           }
          /* usuarios.get(fila).setNombre(JOptionPane.showInputDialog(JOptionPane.showConfirmDialog(null, " Estas seguro de modificar el campo de nombre"), "Selecione el nuevo nombre "));
           usuarios.get(fila).setApellido(JOptionPane.showInputDialog(JOptionPane.showConfirmDialog(null, " Estas seguro de modificar el campo de apellido"), "Selecione el nuevo nombre "));
           usuarios.get(fila).setDoc(Integer.parseInt(JOptionPane.showInputDialog(JOptionPane.showConfirmDialog(null, " Estas seguro de modificar el numero de documento"), "Selecione el nuevo nombre ")));
           //equipos.get(fila).setEstado(JOptionPane.showInputDialog(JOptionPane.showConfirmDialog(null, " Estas seguro de modificar el campo de estado"), "Selecione el nuevo nombre "));
           usuarios.get(fila).setEdad(Integer.parseInt(JOptionPane.showInputDialog(JOptionPane.showConfirmDialog(null, " Esta seguro de modificarel campo de edad"), "Selecione el nuevo nombre")));
        */
       }
           llenarTabla(); 
         
          
      }
      
      /* int fila = jtabla.getSelectedRow();
        if(fila>=0){
            
            usuarios.remove(fila);
            JOptionPane.showMessageDialog(null, "Se elimino con exito ");
           // llenarTabla();
        }
        */
    
    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bbuscar;
    private javax.swing.JButton beliminar;
    private javax.swing.JButton bmodificar;
    private javax.swing.JButton bvolver;
    private javax.swing.JButton guardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jtabla;
    private javax.swing.JTextArea textdatos;
    private javax.swing.JTextField txtapellido;
    private javax.swing.JTextField txtdoc;
    private javax.swing.JTextField txtedad;
    private javax.swing.JTextField txtnombre;
    // End of variables declaration//GEN-END:variables
}
